### ISSUE TITLE
people get stuck

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#13] opened 2017-12-23 11:47 UTC
Sometimes on a corner people get stuck in each other.

The downside of this is that the people who are heading for a room can't get to the room.
this also blocks the room for all other patients

![image](https://user-images.githubusercontent.com/34791332/34319323-2cf2edc4-e7df-11e7-94b1-25d37e2d1323.png)

**Comment by gjdwebserver** [comment] 2017-12-28 19:49
This is a known issue I am looking into a solution

**Comment by Helmond** [comment] 2017-12-30 17:19
with the latest release the people don't get permanently stuck( or at least till now)
i got o couple stuck for about 3 minutes heavily shaking.
it could be they were firmly hugging ;)
they got free after it anyway!

**Comment by Helmond** [comment] 2017-12-30 18:30
update. 
i got some people stuck, actually all of them ( more or less)
because it is in the entrance of the hospital
![image](https://user-images.githubusercontent.com/34791332/34456498-e6662312-ed97-11e7-9cd7-cf70c41d3da5.png)

**Comment by gjdwebserver** [comment] 2017-12-30 18:33
Will look into this issue if I can replicate it, have not seen this behavior myself before.

**Comment by Helmond** [comment] 2017-12-30 18:47
also got someone stuck  half in a wall
![image](https://user-images.githubusercontent.com/34791332/34456577-38419e80-ed9a-11e7-8a48-0f8aac674dde.png)

**Comment by MrTheoW** [comment] 2018-01-07 14:02
Had the same issues, in front of the hospital (18 of 20 patients) and on the corner, the one on the corner i managed to "release" by removing the bench.
Maybe it's a hitbox issue? like a personal space an object shouldn't get into?

**Comment by Helmond** [comment] 2018-01-07 18:32
had the issue of the people in front of the hospital again.
it might occur when 2 people spawn pretty fast after each other

**Comment by gjdwebserver** [comment] 2018-01-08 13:19
Might be that i need to increase the radius of the patient, will look into it, but i never had this problem myself so dont rly know whats happening.

**Comment by gjdwebserver** [comment] 2018-01-08 21:05
I made the AI think the patients are "fatter" I hope this helps to solve the issue.

**Comment by Helmond** [comment] 2018-01-13 15:15
had the issue again today
it happens as follows
at first one patient is standing outside. it doesn't look stuck to something or someone else it is not moving at all. at first other patients can walk around. but then someone else get stuck to the patient that wasn't moving. when there are 3 patients stuck together, all new patients get in pile

**Comment by gjdwebserver** [comment] 2018-01-14 20:52
New version is online (0.3.1) can you check if this bug still occours?

**Comment by stronkie** [comment] 2018-01-16 17:37
Yes still getting stuck.. Maybe make the people like ghosts so they can walk through eachother when they are in limbo

**Comment by gjdwebserver** [comment] 2018-01-16 17:39
I will look into the issue further

**Comment by stronkie** [comment] 2018-01-16 17:45
Well in my case , it started with two people humping eachother.. not getting loose , close to the entrance and the benches... (the ones that already are there when you start the game).. Maybe let us delete those benches .. Also use another way to pathfinding those people.. they always seem to go to a straight line to the exit or whereever.. maybe program the longest way around (like the space before the reception desk).. 

Also add a feature (just for the testing side of things ) to let us delete the people with a ctrl _shift mouseclick or something.. Or at least give us the option to close the hospital so that all the people will leave that are still in there.. Also when people are waiting to long (cause they are in a loop) let them die and despawn > with a bad rep of the hospital.. Each new illness found can give a +10 rep , each cured patient +10 etc.. Let the amonth of patients comming in , depend on the rep of the hospital. If you do not cure the patient intime , we or she will leave and or die with a -rep result (are you dutch and if so , do you need to have close active testers.. I love the game so far )

**Comment by gjdwebserver** [comment] 2018-01-16 17:52
The thing is that I don't have this issue myself, I have never seen it so its kinda hard to debug. Will look into a way to fix this.

The features can you make a separate issue for them for better tracking?

**Comment by Helmond** [comment] 2018-01-16 18:30
i tested today with the new version and still got people stuck
![image](https://user-images.githubusercontent.com/34791332/35005413-93dc2cc2-faf3-11e7-9494-2b09a393512a.png)

i noticed that it almost always happens around the beginning of day 3

**Comment by stronkie** [comment] 2018-01-16 19:53
I have a way to reproduce the issue.. start a new game.. with 3 doctor offices on the left side... (so the left side is totally filled with doctor offices).. Once you have done that (since it is the first thing most patients need to go to.. Also when they go back to their seats and then to the treatment options (2nd room) it will get clusterd there near  the benches... I have tried 3 games now in a row.. all three end up with people stuck..

I can stream a walkthrough and you can see for yourself

**Comment by stronkie** [comment] 2018-01-16 19:54
(since you are a tweaker too  , also dutch here) you could contact me for more help if you want

**Comment by Helmond** [comment] 2018-01-16 20:14
i think the problem isn't that easy and straight forward.
i begin almost all games with 6 doctor offices at the beginning (especially with more starting money feature) and never got people stuck there. 
the fact that @gjdwebserver  can't reproduce this ( or at least till now) hints that it is something system dependent or at somewhat more complex.
in the beginning ( 3/4 versions back or so) i also got people stuck inside the hospital. as for the last 2 versions ( this one and the last) they only get stuck in front of the hospital entrance. i tried different setups with and without waiting benches and i can't see a difference

**Comment by stronkie** [comment] 2018-01-16 20:17
well maybe it is an idea to also post our specs then

I have Ryzen5 1600 , 16 gig mem and windows 10 64 bit and a Nvidia 970

**Comment by Helmond** [comment] 2018-01-16 20:28
2nd generation i5 en intel graphics 3000 or something
to prevent the thing from levitating i set all the settings on low.
the file is on an local ssd and there is 8 GB ram
running on Windows 10 64 bit

**Comment by stronkie** [comment] 2018-01-16 20:37
Well I just made a person stuck.. I created a room and a person was walking where I placed it.. and beng person is stuck.. I deleted the room again , and person is still stuck.. I am streaming it now

http://www.twitch.tv/fhstronkie

**Comment by gjdwebserver** [comment] 2018-01-16 20:38
Thats something I need to implement. ATM just dont build where someone is walkng ;)

**Comment by stronkie** [comment] 2018-01-16 22:02
Ok was able to reproduce the stucking in my stream.. IN the beginning the ambulances got stuck and never got unstuck.. and at the end of my stream people start to get stuck too and it ended wwith them stuck at the entrance.. have fun :)

**Comment by gjdwebserver** [comment] 2018-01-16 22:15
I will look into it

@Helmond and @stronkie Can you check wich illnesses the patients have that get stuck at the entrance for the hospital?

The thing i noticed that you both build the Largest reception and I normaly start with the small one this might have something to do with it, will see if i can debug and reproduce the issue.

I will look into ghosting a patient when its standing to long in the same spot, this might help solve the issue aswell.

**Comment by gjdwebserver** [comment] 2018-01-20 13:10
Ive updated patients so if they stand still and are not in a room (or on a bench) they ignore other patients, this way I hope I've fixed the problem. 

Running simulations atm to see if I need to tune it, but next build will have some improvement (0.3.2)

**Comment by stronkie** [comment] 2018-01-20 22:10
tell us when we can download the latest version

**Comment by stronkie** [comment] 2018-01-20 22:10
ow I have to look what illnesses they have

**Comment by gjdwebserver** [comment] 2018-01-20 22:11
You can download it now, patients getting stuck should be fixed now. 

I don't seem to get patients stuck anymore, while I did before after trying very hard to get them down a very narrow path.

**Comment by gjdwebserver** [comment] 2018-02-19 13:03
Did not get an update for a month and cannot reproduce the issue anymore. closing it.

**Closed as completed by gjdwebserver** 2018-02-19 13:03 UTC
Labels: bug
